# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Run the welcome/run job in its own container
jobs:
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: install conda
        command: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
          echo 'export PATH="~/miniconda/bin:$PATH"' >> $BASH_ENV
